version: '3.9'

services:
  app:
    build: .
    volumes:
      - ./app:/app
    environment:
      - OPENAI_API_KEY=
    ports:
      - 8000:8000
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
